language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_script:
    - git clone https://github.com/octobercms/october.git
    - mkdir -p ./october/plugins/pkleindienst/githubprojects
    - mv !(october) october/plugins/pkleindienst/githubprojects
    - cd october
    - travis_retry composer install --no-interaction --prefer-source
    - cd plugins/pkleindienst/githubprojects
    - composer install

script:
    #- vendor/bin/phpcs --standard=psr2 --ignore=*/tests/*,*/vendor/* .
    - ../../../vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - ./vendor/bin/test-reporter